## Copyright 2024 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: (Internal) CI workflow
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-rockylinux8:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      project: oidn
      image: oidn/rockylinux:8.8
      dpcpp-version: intel-llvm/nightly-2023-10-26-rk
      cmd: scripts/build.py install --full
      artifact-out: build-rockylinux8
      artifact-path: build install deps

  test-rockylinux8-cuda:
    needs: build-rockylinux8
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      project: oidn
      runs-on: '[ "Linux", "gpu_nvidia" ]'
      image: oidn/ubuntu:22.04
      options: --gpus all
      artifact-in: build-rockylinux8
      artifact-out: test-rockylinux8-cuda
      artifact-path: test.log
      artifact-on-failure: true
      cmd: scripts/test.py --device cuda --memcheck --log test.log

  test-rockylinux8-hip:
    needs: build-rockylinux8
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      project: oidn
      runs-on: '[ "Linux", "gpu_amd" ]'
      image: oidn/rockylinux:8.8
      options: --device=/dev/kfd --device=/dev/dri
      artifact-in: build-rockylinux8
      artifact-out: test-rockylinux8-hip
      artifact-path: test.log
      artifact-on-failure: true
      cmd: scripts/test.py --device hip --memcheck --log test.log