## Copyright 2024 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: (Internal) CI workflow
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-rockylinux8:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      project: oidn
      image: oidn/rockylinux:8.8
      dpcpp-version: intel-llvm/nightly-2023-10-26-rk
      cmd: scripts/build.py install --full
      artifact-out: build-rockylinux8
      artifact-path: build install deps

  test-rockylinux8-bmg:
    needs: build-rockylinux8
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      project: oidn
      runs-on: '[ "Linux", "bmg" ]'
      image: oidn/ubuntu:22.04
      options: --device=/dev/dri
      artifact-in: build-rockylinux8
      artifact-out: test-rockylinux8-bmg
      artifact-path: test.log
      artifact-on-failure: true
      cmd: scripts/test.py --device sycl --log test.log

  build-windows:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      project: oidn
      runs-on: '[ "Windows", "cuda", "hip" ]'
      msvc-version: "2022"
      dpcpp-version: intel-llvm/nightly-2023-10-26-rk
      ocloc-version: oneAPI/ocloc/2025.0
      artifact-out: build-windows
      artifact-path: build install
      cmd: python scripts/build.py install --full

  test-windows-adl:
    needs: build-windows
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      project: oidn
      runs-on: '[ "Windows", "igpu", "adl" ]'
      env-from-files: ./.github/workflows/gfx-windows-public.env
      artifact-in: build-windows
      artifact-out: test-windows-adl
      artifact-path: test.log
      artifact-on-failure: true
      cmd: python scripts/test.py --device sycl --log test.log

  test-windows-dg2:
    needs: build-windows
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      project: oidn
      runs-on: '[ "Windows", "dg2", "NAS" ]'
      env-from-files: ./.github/workflows/gfx-windows-public.env
      artifact-in: build-windows
      artifact-out: test-windows-dg2
      artifact-path: test.log
      artifact-on-failure: true
      cmd: python scripts/test.py --device sycl --log test.log

  test-windows-bmg:
    needs: build-windows
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      project: oidn
      runs-on: '[ "Windows", "bmg", "NAS" ]'
      env-from-files: ./.github/workflows/gfx-windows-public-bmg.env
      artifact-in: build-windows
      artifact-out: test-windows-bmg
      artifact-path: test.log
      artifact-on-failure: true
      cmd: python scripts/test.py --device sycl --log test.log